spring:
  application:
    name: user-service-cashpilot

  datasource:
    url: jdbc:postgresql://localhost:5432/cashpilot-user-service-postgresql
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver


  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/cashpilot

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 9094