spring:
  application:
    name: user-service-cashpilot

  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        register: true
        health-check-path: /actuator/health
        health-check-interval: 15s
        health-check-port: 9094

  datasource:
    url: jdbc:postgresql://localhost:5432/cashpilot-user-service-postgresql
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver


  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/cashpilot

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


server:
  port: 9094

grpc:
  server:
    port: 9090

management:
  endpoints:
    web:
      exposure:
        include: "health"


logging:
  level:
    net.devh.boot.grpc: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG