spring:
  application:
    name: user-service-cashpilot

  cloud:
    consul:
      host: ${SPRING_CLOUD_CONSUL_HOST}
      port: ${SPRING_CLOUD_CONSUL_PORT}
      discovery:
        register: true
        health-check-path: /actuator/health
        health-check-interval: 15s
        health-check-port: ${SERVER_PORT}

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver


  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUERURI}

  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDLAUTO}
    show-sql: ${SPRING_JPA_SHOWSQL}

  flyway:
    user: admin
    password: admin
    url: ${DB_URL}
    locations: classpath:db/migration

server:
  port: ${SERVER_PORT}

grpc:
  server:
    port: ${GRPC_SERVER_PORT}

management:
  endpoints:
    web:
      exposure:
        include: "health"


logging:
  level:
    net.devh.boot.grpc: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
